### PR TITLE
Fix secret revoke error with user_token

### LINKED ISSUE #236: Error on reading artifactory/config/admin path
**Describe the bug**
After the plugin is up and running on the vault instance, when trying to do a read of the "artifactory/config/admin" path, the following error is output:
```
Error reading artifactory/config/admin: Error making API request.

URL: GET https://vault.csm.volvocars.biz/v1/artifactory/config/admin
Code: 500. Errors:

* 1 error occurred:
        * empty access token not allowed
```

This instance is configured with the exceptional case of a configuration without a access token:
`vault write artifactory/config/admin url=***`
`vault write artifactory/config/admin use_expiring_tokens=true`
`vault write artifactory/config/admin default_description="Generated by Vault" max_ttl=14400 default_ttl=3600`
`vault write artifactory/config/user_token use_expiring_tokens=true`
`vault write artifactory/config/user_token default_description="Generated by Vault" max_ttl=14400 default_ttl=3600`
`vault write artifactory/config/user_token scope="applied-permissions/user"`
`vault write artifactory/config/user_token audience="jfrt@* jfxr@*"`

Artifactory version: 7.98.7
Vault version: 1.18.2
Vault plugin version: 1.8.4

**To Reproduce**
1. Initiate vault instance and configure artifactory plugin on one of the paths as above
2. Do the CLI "vault read artifactory/config/admin"

**Requirements for and issue**
- [x] A description of the bug
- [x] A fully functioning vault configuration snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [x] Your version of vault
- [x] Your version of vault plugin

**Expected behavior**
It's expected to have the full output of the key and values of the artifactory/config/admin

**Screenshots**
Image

### LINKED ISSUE #237: Failed to revoke lease due to empty access token not allowed
**Describe the bug**
The path under the "artifactory/user_token/<name>", is being managed by the artifactory plugin. Every time a refresh token is request, a lease is created in Vault, but due to a error on "missing access_token", related in the https://github.com/jfrog/vault-plugin-secrets-artifactory/issues/236, the following error shows every time the vault automatically tries to revoke the lease:

`"2025-01-03T14:27:12.776Z [ERROR] expiration: failed to revoke lease: lease_id=artifactory/user_token/bppmanap/0dAs9vq5DZEHNuK6fs9aQ6is error="failed to revoke entry: resp: (*logical.Response)(nil) err: empty access token not allowed" attempts=4 next_attempt=3m46.307019948s"`

This is making the lease count in vault increase reaching the max lease count on it, disabling the users from logging in.

This instance is configured with the exceptional case of a configuration without a access token:
`vault write artifactory/config/admin url=***`
`vault write artifactory/config/admin use_expiring_tokens=true`
`vault write artifactory/config/admin default_description="Generated by Vault" max_ttl=14400 default_ttl=3600`
`vault write artifactory/config/user_token use_expiring_tokens=true`
`vault write artifactory/config/user_token default_description="Generated by Vault" max_ttl=14400 default_ttl=3600`
`vault write artifactory/config/user_token scope="applied-permissions/user"`
`vault write artifactory/config/user_token audience="jfrt@* jfxr@*"`

Artifactory version: 7.98.7
Vault version: 1.18.2
Vault plugin version: 1.8.4

**To Reproduce**
1. Initiate vault instance and configure artifactory plugin on one of the paths as above
2. Do the CLI "vault write artifactory/config/user_token/<name>" and wait overtime for the lease to be created and revoked

**Requirements for and issue**
- [ ] A description of the bug
- [ ] A fully functioning vault configuration snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [ ] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [ ] Your version of vault
- [ ] Your version of vault plugin

### PR DESCRIPTION
**Pull request by alexhung**
Fix #237 

Now secret lease revoke will check for empty access token from admin config and fall back to user_token config if it was empty.

Improve logging for TTL values.

Also fix errors when reading admin config if `access_token` is not set. Fixes #236

### CODE REVIEW

**Review by benharosh — DISMISSED** [review]

**Comment by Claudiordev** [comment]
Hi,

I builded this branch artifactory plugin and test it locally, still having an error on the leases being revoked as following:

`2025-01-14T15:34:49.627+0100 [ERROR] expiration: failed to revoke lease: lease_id=artifactory/user_token/cfreita1/gom1W5LMI39gBib63zs0MscK error="failed to revoke entry: resp: &logical.Response{Secret:<nil>, Auth:<nil>, Data:map[string]interface {}{\"error\":\"admin access_token is not configured\"}, Redirect:\"\", Warnings:[]string(nil), WrapInfo:(*wrapping.ResponseWrapInfo)(nil), Headers:map[string][]string(nil), MountType:\"\"} err: %!w(<nil>)" attempts=2 next_attempt=20.774219754s`

File: secret_access_token.go [hunk 1]
```diff
@@ -74,19 +84,47 @@ func (b *backend) secretAccessTokenRenew(ctx context.Context, req *logical.Reque
...
 	}
 
 	if config == nil {
 		return logical.ErrorResponse("backend not configured"), nil
 	}
 
+	// logger.Debug("request", "Path", req.Path, "Secret.InternalData", req.Secret.InternalData)
+
+	if config.AccessToken == "" {
+		if strings.Contains(req.Path, "token/") {
```
Comment (Claudiordev) [inline secret_access_token.go:102]: Removing this block should succesfully remove the error hitting on the leases

**Comment by alexhung** [comment]
@Claudiordev Thanks for testing/verifying. I've improved the path matching. This should work correctly now.

**Review by benharosh — APPROVED** [review]

**Review by danielmkn — APPROVED** [review]
